# Generated by Django 2.2.5 on 2020-03-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_votes_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes_ip',
            old_name='Voted_question',
            new_name='voted_question',
        ),
    ]
